FROM openjdk:21-jdk-slim

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN apt-get update && apt-get install -y maven && \
    mvn dependency:go-offline -B

EXPOSE 8080

CMD ["mvn", "spring-boot:run"]