spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: 27017
      database: app_db
      username: app_user
      password: app_password
      authentication-database: app_db
  application:
    name: backend
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

server:
  port: 8080

logging:
  level:
    camt.scott2.backend: DEBUG
    org.springframework.data.mongodb: DEBUG